In [ ]:
cd "C:\Users\Shreya\Desktop\Final Year Project"

C:\Users\Shreya\Desktop\Final Year Project


In [ ]:
import pickle

In [ ]:
import numpy as np

# Load the stored model with weights of the nn

In [ ]:
stored_model = 'finalized_model1.sav'

In [ ]:
loaded_model = pickle.load(open(stored_model, 'rb'))

# Load the test data 

In [ ]:
filename='test_data.npy'
data = np.load(filename, mmap_mode="r")
print(data)

[[ 1.01870695  0.36881128  1.02708454 ... -0.38026549  1.39509644
   0.09046747]
 [ 0.33871989  0.92815522  1.30958176 ...  0.46560205  0.73683691
   0.84406702]
 [-0.69522074 -0.29769375  1.5947714  ...  1.06862121  1.70877991
  -1.04010822]
 ...
 [-0.4537175  -0.76797932 -1.0258432  ... -1.65859927  0.10390658
   1.02615347]
 [ 0.84467276  0.35454869  0.4189764  ... -0.32201403  1.12611063
  -2.71759391]
 [-0.05162412  0.88216965  0.67633064 ...  1.76659647 -0.19494812
   0.47883118]]


# Predict

In [ ]:
result = loaded_model.predict(data)
'for single input give it as data[1:2]'

In [ ]:
print(result)

[[1.35555701e-05 2.46477372e-04 9.99636292e-01 1.03713610e-04]
 [1.37211886e-04 3.59560016e-12 6.28664100e-04 9.99234080e-01]
 [2.68758566e-04 1.42404078e-05 9.70055938e-01 2.96610631e-02]
 [9.97985959e-01 2.93223511e-05 1.26509272e-04 1.85834360e-03]
 [5.65140182e-03 8.82443607e-01 1.11902080e-01 2.82968495e-06]
 [1.23409656e-04 3.52605532e-12 6.61412370e-04 9.99215126e-01]
 [3.06063332e-03 6.92155083e-07 1.27425179e-01 8.69513512e-01]
 [3.77110630e-01 3.37947041e-01 2.83830285e-01 1.11205946e-03]
 [9.18265214e-05 9.20878825e-12 1.24900567e-03 9.98659134e-01]
 [6.29714981e-04 3.39131973e-10 2.40369979e-03 9.96966541e-01]
 [5.07660443e-03 9.64430213e-01 3.04926317e-02 6.12398537e-07]
 [1.61315768e-03 3.31050352e-08 1.73441805e-02 9.81042624e-01]
 [1.46718754e-03 7.94131072e-09 7.05980882e-03 9.91472960e-01]
 [7.98249364e-01 1.99986532e-01 1.74826710e-03 1.58433268e-05]
 [7.93691026e-04 9.88850296e-01 1.03560379e-02 2.21779466e-08]
 [7.41053373e-04 2.56894550e-09 6.07760204e-03 9.931812

In [ ]:
pred = (result == result.max(axis=1)[:,None]).astype(int)

In [ ]:
'prints the predicted class'
print(pred.argmax(axis=1))

[2 3 2 0 1 3 3 0 3 3 1 3 3 0 1 3 0 1 3 0 1 3 2 0 2 0 3 3 1 1 1 0 1 3 1 3 1
 3 1 3 3 1 2 2 2 1 1 1 0 3 0 1 0 1 3 2 2 2]
